// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxf2543rMyL98-5Vi6JIRpTpHg0q6hank',
    appId: '1:720242368311:web:d597dc9052183fe85c44b2',
    messagingSenderId: '720242368311',
    projectId: 'group-chat-75971',
    authDomain: 'group-chat-75971.firebaseapp.com',
    storageBucket: 'group-chat-75971.appspot.com',
    measurementId: 'G-QRCCWLKHWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_p0gi0cVl50mlfyGekalU_AxiSwqpHOQ',
    appId: '1:720242368311:android:f80bc515596d15be5c44b2',
    messagingSenderId: '720242368311',
    projectId: 'group-chat-75971',
    storageBucket: 'group-chat-75971.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr9qsgoExnF9pL7e6mnJa1ppCLsIGYwDo',
    appId: '1:720242368311:ios:d13456441d2a433c5c44b2',
    messagingSenderId: '720242368311',
    projectId: 'group-chat-75971',
    storageBucket: 'group-chat-75971.appspot.com',
    iosClientId: '720242368311-eup3jft8qg97laihb6ukkf1da08d4jgm.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr9qsgoExnF9pL7e6mnJa1ppCLsIGYwDo',
    appId: '1:720242368311:ios:d13456441d2a433c5c44b2',
    messagingSenderId: '720242368311',
    projectId: 'group-chat-75971',
    storageBucket: 'group-chat-75971.appspot.com',
    iosClientId: '720242368311-eup3jft8qg97laihb6ukkf1da08d4jgm.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupChat',
  );
}
